# Generated by Django 2.0.5 on 2019-09-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=80)),
                ('b_thumbnail', models.CharField(max_length=125)),
                ('b_price', models.CharField(max_length=20)),
                ('b_stock', models.BooleanField()),
                ('b_product_descripcion', models.TextField()),
                ('b_upc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='fk_c_id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Categories'),
        ),
    ]
