# Generated by Django 2.0.5 on 2019-09-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='fk_c_id_category',
            new_name='categories',
        ),
    ]
