# Generated by Django 2.0.5 on 2019-09-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190904_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='b_stock',
            field=models.IntegerField(),
        ),
    ]
