# Generated by Django 2.0.5 on 2019-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190906_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='b_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='b_title',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='books',
            name='b_upc',
            field=models.CharField(max_length=16),
        ),
    ]
